In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
random_mat = np.random.randint(-1, 10, (100, 100))

In [4]:
sorting_order = list(zenumerate((100, 100)))
sorting_order = np.array(sorting_order)

In [5]:
sorting_order

array([[ 0,  0],
       [ 1,  0],
       [ 0,  1],
       ..., 
       [99, 98],
       [98, 99],
       [99, 99]])

In [6]:
index_array = np.arange(100*100)
index_matrix = index_array.reshape((100, 100))
ordered_index_matrix = index_matrix.copy()

In [7]:
zorder(ordered_index_matrix)

In [8]:
index_matrix

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [9]:
ordered_index_matrix

array([[   0,    2,    8, ..., 8450, 8456, 8458],
       [   1,    3,    9, ..., 8451, 8457, 8459],
       [   4,    6,   12, ..., 8454, 8460, 8462],
       ..., 
       [5121, 5123, 5129, ..., 9987, 9993, 9995],
       [5124, 5126, 5132, ..., 9990, 9996, 9998],
       [5125, 5127, 5133, ..., 9991, 9997, 9999]])

Ok that works fine.

In [10]:
correct_list = ordered_index_matrix.ravel()

In [11]:
grid_size = 100
num_balls = 800

In [12]:
positions_in_grid = np.random.randint(0, grid_size, (num_balls, 2))
grid = -1*np.ones((grid_size, grid_size), dtype=np.int)
grid[positions_in_grid[:, 0], positions_in_grid[:, 1]] = np.arange(num_balls)

In [13]:
positions_in_grid

array([[11, 88],
       [88, 79],
       [33, 40],
       ..., 
       [ 5, 91],
       [27, 59],
       [35,  4]])

In [14]:
grid

array([[ -1,  -1,  -1, ...,  -1,  -1, 658],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1],
       ..., 
       [ -1,  -1, 776, ...,  -1,  -1,  -1],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1],
       [ -1,  -1,  -1, ...,  -1,  -1,  -1]])

We need to convert the positions in the grid to a logical index.

In [15]:
logical_positions = grid_size * positions_in_grid[:, 0] + positions_in_grid[:, 1]

We now get the order they are supposed to have.

In [19]:
order_fixer = np.argsort(correct_list[logical_positions])

In [23]:
order_fixer

array([441, 298, 196, 261, 487, 252,  64, 736, 400, 579, 470, 433, 497,
       792, 310, 272, 300, 739,  27, 661, 575, 462, 275, 194,  82, 604,
       618, 761, 329, 237, 383, 721, 506, 362, 465, 527, 373, 691, 455,
       204,  58, 123, 639, 380, 785, 612, 203, 687, 685, 381, 231, 420,
       562, 303, 759, 313, 202, 153,  70, 675, 557, 635, 556, 288, 616,
       468, 352, 192, 495, 643, 396, 243, 200, 490, 367, 302, 648, 104,
       105, 366, 799,  36, 138, 645,  46,  16, 269, 394, 419, 154, 413,
       316, 244, 369, 238, 543,  31, 128, 199, 390, 403, 703, 332,  23,
        53, 360, 322, 597, 587, 334, 432, 569, 598, 532, 190, 720, 299,
       728, 515,  59, 489, 114, 748, 296, 521, 351, 382, 258,  85, 700,
       277, 447,  67, 765, 417, 735,  49, 502,  14, 291, 488,  94, 181,
       131,   5, 119, 328, 763, 358, 671, 492, 276, 260, 376, 169, 621,
       132, 777, 346, 216, 229,  33, 582, 209, 714,  93, 449, 133, 210,
       171, 529, 771, 555, 586, 404, 227, 336, 581, 422, 577, 76

In [22]:
positions_in_grid[order_fixer]

array([[ 7,  0],
       [ 5,  2],
       [ 7,  3],
       ..., 
       [89, 98],
       [93, 98],
       [97, 96]])

Yes that's it . Cool. Got it.

How do we update the grid now, however? I'm still confused about that.

In [30]:
np.ix_(positions_in_grid, 160)

ValueError: Cross index must be 1 dimensional

In [32]:
blerp = np.arange(grid_size*grid_size)

In [33]:
blerp.reshape((grid_size, grid_size))

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [38]:
blerp = 3
arr = np.arange(blerp*blerp)
mat = arr.reshape((blerp, blerp))

In [39]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
zorder(mat)

In [41]:
mat

array([[0, 2, 6],
       [1, 3, 7],
       [4, 5, 8]])